version: '3.7'

services:
  # Build the app services
  app:
    build: app
    environment:
     - SECRET_KEY=${SECRET_KEY}
     - DB_HOST=${DB_HOST}
     - DATABASE=${DATABASE}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
     - AWS_SECRET_KEY=${AWS_SECRET_KEY}
     - AWS_S3_LINK=${AWS_S3_LINK}
  nginx:
    container_name: nginx
    build: nginx
    # Bind the port 80 of container to machine port 80
    ports:
      - 80:80
    # Make app as nginx dependency service
    depends_on:
      - app
